### ISSUE TITLE
the use of DataSourceConfig

### ISSUE THREAD

**Issue by amirensit** [souzadriano/jhipster-multitenant#1]
Hi.

Can you explain please what is the use behind `DataSourceConfig` ?

**Comment by souzadriano** [comment]
Hi @amirensit ,

The DataSourceConfig (table mt_datasource_config) contain all the databases (tenants) that application will connect. You can add the tenants through the application.

Example: 
id | name     | url                                                                  | username | password | initialize
1  | tenant 1 | jdbc:postgresql://localhost:5432/tenant1  | tenant1      | tenant2    | true
2 | tenant 2 | jdbc:postgresql://localhost:5432/tenant2 | tenant2      | tenant2    | true
3 | tenant 3 | jdbc:postgresql://localhost:5432/tenant3 | tenant3      | tenant3    | false

**Comment by amirensit** [comment]
thanks !

**Comment by amirensit** [comment]
one last question : 

which way did you implement : 

- Separate databases

- Separate schemas

- Shared schema

best regards

**Comment by souzadriano** [comment]
> one last question :
> 
> which way did you implement :
> 
> * Separate databases
> * Separate schemas
> * Shared schema
> 
> best regards

I implemented separate databases.
